### ISSUE TITLE
 urn:cts:greekLit:tlg5026.msA.GKolov: 5.1031

### ISSUE THREAD

**Issue by GKolov** [homermultitext/scholia-english#76]
Lemma (leave blank if no lemma): ἀντικρὺ δὲ διέσχε
 
Comment:
It is accented with an acute on the final syllable and it is augmented; when it has the σ , it is contracted and pronounced with an accent on the final syllable. We will  explain the reason in the [work] Peri epirrhēmatos.

**Comment by caseydue** [comment]
(See if you think this is right. Dickey says the word βαρύνω pronounce _without_ an accent.)

Lemma (leave blank if no lemma): ἀντικρὺ δὲ διέσχε

Comment:
It is accented with an acute and it is augmented. Whenever it has the sigma, it is short and pronounced without an accent on the final syllable. We will explain the reason in the [work] Peri epirrhēmatos ("On the Adverb").

**Comment by GKolov** [comment]
Yes, yes, yes, yes!! ( βαρύνω=pronounce without an accent on the final syllable, mark the final syllable with a grave accent, have no accent on the final syllable!!

**Comment by caseydue** [comment]
Lemma (leave blank if no lemma): ἀντικρὺ δὲ διέσχε

Comment:
It is accented with an acute and it is augmented. Whenever it has the sigma, it is short and pronounced without an accent on the final syllable. We will explain the reason in the [work] Peri epirrhēmatos ("On the Adverb").
